"""
Prometheus metrics for the trading platform.
Reference: SYSTEM_ARCHITECTURE.md §3.7
"""

import logging
from prometheus_client import Counter, Histogram, Gauge, Info

logger = logging.getLogger(__name__)


# ─── Order Metrics ────────────────────────────────────────────────────
ORDERS_PLACED = Counter(
    "trading_orders_placed_total",
    "Total orders placed",
    ["exchange", "order_type", "product_type", "side"]
)

ORDERS_REJECTED = Counter(
    "trading_orders_rejected_total",
    "Total orders rejected",
    ["exchange", "reason"]
)

ORDERS_FILLED = Counter(
    "trading_orders_filled_total",
    "Total orders filled",
    ["exchange", "side"]
)

ORDER_LATENCY = Histogram(
    "trading_order_latency_seconds",
    "Order placement latency (API call to response)",
    ["exchange"],
    buckets=[0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0]
)

SLIPPAGE = Histogram(
    "trading_slippage_bps",
    "Order slippage in basis points",
    ["exchange", "order_type"],
    buckets=[0, 1, 2, 5, 10, 25, 50, 100]
)


# ─── Data / WebSocket Metrics ────────────────────────────────────────
WS_CONNECTIONS = Gauge(
    "trading_websocket_connections",
    "Active WebSocket connections",
    ["type"]  # "broker" or "ui"
)

WS_RECONNECTS = Counter(
    "trading_websocket_reconnects_total",
    "Total broker WebSocket reconnect events"
)

WS_SUBSCRIBE_ERRORS = Counter(
    "trading_websocket_subscribe_errors_total",
    "Total broker WebSocket subscription errors"
)

TICKS_RECEIVED = Counter(
    "trading_ticks_received_total",
    "Total ticks received from broker WebSocket"
)

TICKS_DROPPED = Counter(
    "trading_ticks_dropped_total",
    "Ticks dropped due to backpressure"
)

TICKS_INVALID = Counter(
    "trading_ticks_invalid_total",
    "Ticks dropped due to malformed payload"
)

BRIDGE_QUEUE_SIZE = Gauge(
    "trading_bridge_queue_size",
    "Current size of the data bridge queue"
)

TICK_LATENCY = Histogram(
    "trading_tick_latency_ms",
    "Tick processing latency in milliseconds",
    buckets=[1, 2, 5, 10, 25, 50, 100]
)


# ─── Strategy Metrics ────────────────────────────────────────────────
ACTIVE_STRATEGIES = Gauge(
    "trading_active_strategies",
    "Number of active strategies"
)

STRATEGY_SIGNALS = Counter(
    "trading_strategy_signals_total",
    "Signals generated by strategies",
    ["strategy_name", "signal_type"]  # BUY, SELL, HOLD
)

STRATEGY_EXECUTION_TIME = Histogram(
    "trading_strategy_execution_seconds",
    "Strategy on_bar/on_tick execution time",
    ["strategy_name"],
    buckets=[0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1]
)


# ─── API Metrics ─────────────────────────────────────────────────────
API_REQUESTS = Counter(
    "trading_api_requests_total",
    "Total API requests",
    ["method", "path", "status_code"]
)

API_LATENCY = Histogram(
    "trading_api_latency_seconds",
    "API request latency",
    ["method", "path"],
    buckets=[0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0]
)


# ─── System Metrics ──────────────────────────────────────────────────
BROKER_AUTH_STATUS = Gauge(
    "trading_broker_auth_status",
    "Broker authentication status (1=authenticated, 0=not)"
)

RATE_LIMITER_TOKENS = Gauge(
    "trading_rate_limiter_tokens",
    "Available rate limiter tokens",
    ["limiter_name"]
)

SYSTEM_INFO = Info(
    "trading_platform",
    "Trading platform version info"
)


# ─── Portfolio Metrics ───────────────────────────────────────────────
PORTFOLIO_VALUE = Gauge(
    "trading_portfolio_value",
    "Current portfolio value in INR"
)

OPEN_POSITIONS = Gauge(
    "trading_open_positions",
    "Number of open positions"
)

DAILY_PNL = Gauge(
    "trading_daily_pnl",
    "Daily realized P&L in INR"
)


def init_metrics():
    """Initialize static metric values on startup."""
    SYSTEM_INFO.info({
        "version": "1.0.0",
        "broker": "angel_one",
        "engine": "hybrid",
    })
    WS_CONNECTIONS.labels(type="broker").set(0)
    WS_CONNECTIONS.labels(type="ui").set(0)
    BROKER_AUTH_STATUS.set(0)
    BRIDGE_QUEUE_SIZE.set(0)
    ACTIVE_STRATEGIES.set(0)
    logger.info("✅ Prometheus metrics initialized")
